// tracker_blocklist.cc - built-in tracker protection (see header)

#include "security/tracker_blocklist.h"

#include <algorithm>
#include <cctype>
#include <cstdint>
#include <unordered_set>

// Generated by CMake from browser/blocklist/trackers.txt.
#include "security/tracker_blocklist_data.inc"

namespace lethe {

namespace {

std::string trim(const std::string& s) {
    size_t b = 0, e = s.size();
    while (b < e && std::isspace(static_cast<unsigned char>(s[b]))) b++;
    while (e > b && std::isspace(static_cast<unsigned char>(s[e - 1]))) e--;
    return s.substr(b, e - b);
}

std::string lower(std::string s) {
    for (char& c : s) c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
    return s;
}

bool validDomainChar(char c) {
    return std::isalnum(static_cast<unsigned char>(c)) || c == '.' || c == '-';
}

} // namespace

std::string regexEscape(const std::string& in) {
    std::string out;
    out.reserve(in.size() * 2);
    for (char c : in) {
        switch (c) {
            case '.': case '\\': case '+': case '*': case '?': case '[': case ']':
            case '(': case ')': case '{': case '}': case '|': case '^': case '$':
            case '/':
                out += '\\';
                out += c;
                break;
            default:
                out += c;
        }
    }
    return out;
}

TrackerBlocklist parseTrackerBlocklist(const std::string& text) {
    TrackerBlocklist list;
    // This parser runs during browser startup and its output is immutable for
    // the lifetime of the process.  Ordered sets only add O(log n) tree
    // insertion plus a node allocation for each entry; ordering is already
    // preserved by the vectors below, so hash sets give the same semantics
    // with substantially less startup bookkeeping.
    std::unordered_set<std::string> seenDomains, seenPaths;
    seenDomains.reserve(256);
    seenPaths.reserve(32);
    size_t pos = 0;
    while (pos <= text.size()) {
        size_t nl = text.find('\n', pos);
        if (nl == std::string::npos) nl = text.size();
        std::string line = trim(text.substr(pos, nl - pos));
        pos = nl + 1;
        const size_t hash = line.find('#');
        if (hash != std::string::npos) line = trim(line.substr(0, hash));
        if (line.empty()) continue;
        line = lower(line);
        // Strip an accidental scheme or wildcard prefix.
        for (const char* p : {"https://", "http://", "*.", "."}) {
            const size_t n = std::char_traits<char>::length(p);
            if (line.compare(0, n, p) == 0) { line = line.substr(n); break; }
        }
        if (line.empty()) continue;
        const size_t slash = line.find('/');
        const std::string host = slash == std::string::npos ? line : line.substr(0, slash);
        if (host.empty() || host.find('.') == std::string::npos) continue;
        if (!std::all_of(host.begin(), host.end(), validDomainChar)) continue;
        if (slash != std::string::npos && slash + 1 < line.size()) {
            if (seenPaths.insert(line).second) list.pathPatterns.push_back(line);
        } else if (seenDomains.insert(host).second) {
            list.domains.push_back(host);   // "host/" is just a host
        }
    }
    return list;
}

const TrackerBlocklist& builtinTrackerBlocklist() {
    static const TrackerBlocklist list = parseTrackerBlocklist(kBuiltinTrackerBlocklistText);
    return list;
}

namespace {

std::string buildTrackerContentRulesJson(const TrackerBlocklist& list) {
    std::string json = "[";
    // Avoid repeated growth while materializing the rule document.  The
    // exact size is data-dependent, but a conservative estimate keeps the
    // normal built-in list on one allocation without retaining a huge
    // over-reserved buffer for custom lists.
    const size_t estimated = list.domains.size() * 96 +
                             list.pathPatterns.size() * 128 + 2;
    json.reserve(estimated);
    bool first = true;
    // The regex is built with real single backslashes, then JSON-escaped
    // (each backslash doubled) when written into the rule document.
    auto jsonEscape = [](const std::string& in) {
        std::string out;
        for (char c : in) { if (c == '\\' || c == '"') out += '\\'; out += c; }
        return out;
    };
    auto rule = [&](const std::string& regex) {
        if (!first) json += ",";
        first = false;
        json += "{\"trigger\":{\"url-filter\":\"" + jsonEscape(regex) +
                "\",\"load-type\":[\"third-party\"]},\"action\":{\"type\":\"block\"}}";
    };

    // Keep one anchored URL rule per tracker domain. WebKit's `if-domain`
    // trigger looks attractive as a faster lookup, but its interaction with
    // `load-type: third-party` is not consistent across the WebKit versions
    // Lethe supports (notably fetch/XHR loads). A compiled URL regex is a
    // little more work in the content blocker, but it is deterministic and
    // keeps the security boundary intact for every resource type.
    if (!list.domains.empty()) {
        for (const auto& domain : list.domains) {
            rule("^https?://([^/]+\\.)?" + regexEscape(domain) + "[/:]");
        }
    }

    // Path entries cannot be expressed by if-domain. WebKit's content
    // blocker regex dialect does not support disjunctions (`|`), so do not
    // combine these entries into one alternation: that causes the entire
    // path-rule set to be rejected and silently drops those protections.
    // There are intentionally only a small number of path-specific entries,
    // so one anchored rule per entry is both correct and bounded.
    for (const auto& p : list.pathPatterns) {
        const size_t slash = p.find('/');
        if (slash == std::string::npos) continue;
        rule("^https?://([^/]+\\.)?" +
             regexEscape(p.substr(0, slash)) +
             regexEscape(p.substr(slash)));
    }
    json += "]";
    return json;
}

} // namespace

std::string trackerContentRulesJson(const TrackerBlocklist& list) {
    // The built-in list is immutable for the lifetime of the process and is
    // requested by both engine shells during startup. Cache its serialized
    // WebKit representation so CEF/WebKit setup does not repeatedly rebuild
    // hundreds of regex rules and allocate a large temporary JSON string.
    // Custom lists retain the original value-semantics and are generated on
    // demand.
    if (&list == &builtinTrackerBlocklist()) {
        static const std::string cached = buildTrackerContentRulesJson(list);
        return cached;
    }
    return buildTrackerContentRulesJson(list);
}

std::string trackerRulesIdentifier(const TrackerBlocklist& list) {
    // FNV-1a over the canonical entry list: cheap, stable across runs, and
    // different whenever the list content differs.
    uint64_t h = 1469598103934665603ULL;
    auto mix = [&](const std::string& s) {
        for (unsigned char c : s) { h ^= c; h *= 1099511628211ULL; }
        h ^= '\n'; h *= 1099511628211ULL;
    };
    for (const auto& d : list.domains) mix(d);
    for (const auto& p : list.pathPatterns) mix("/" + p);
    static const char* hex = "0123456789abcdef";
    // Bump the format identifier whenever the compiled representation changes
    // so WebKit cannot silently reuse a stale filter from its on-disk cache.
    std::string id = "lethe-trackers-v5-";
    for (int i = 60; i >= 0; i -= 4) id += hex[(h >> i) & 15];
    return id;
}

} // namespace lethe
