// tracker_blocklist.cc - built-in tracker protection (see header)

#include "security/tracker_blocklist.h"

#include <algorithm>
#include <cctype>
#include <cstdint>
#include <set>

// Generated by CMake from browser/blocklist/trackers.txt.
#include "security/tracker_blocklist_data.inc"

namespace lethe {

namespace {

std::string trim(const std::string& s) {
    size_t b = 0, e = s.size();
    while (b < e && std::isspace(static_cast<unsigned char>(s[b]))) b++;
    while (e > b && std::isspace(static_cast<unsigned char>(s[e - 1]))) e--;
    return s.substr(b, e - b);
}

std::string lower(std::string s) {
    for (char& c : s) c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
    return s;
}

bool validDomainChar(char c) {
    return std::isalnum(static_cast<unsigned char>(c)) || c == '.' || c == '-';
}

} // namespace

std::string regexEscape(const std::string& in) {
    std::string out;
    out.reserve(in.size() * 2);
    for (char c : in) {
        switch (c) {
            case '.': case '\\': case '+': case '*': case '?': case '[': case ']':
            case '(': case ')': case '{': case '}': case '|': case '^': case '$':
            case '/':
                out += '\\';
                out += c;
                break;
            default:
                out += c;
        }
    }
    return out;
}

TrackerBlocklist parseTrackerBlocklist(const std::string& text) {
    TrackerBlocklist list;
    std::set<std::string> seenDomains, seenPaths;
    size_t pos = 0;
    while (pos <= text.size()) {
        size_t nl = text.find('\n', pos);
        if (nl == std::string::npos) nl = text.size();
        std::string line = trim(text.substr(pos, nl - pos));
        pos = nl + 1;
        const size_t hash = line.find('#');
        if (hash != std::string::npos) line = trim(line.substr(0, hash));
        if (line.empty()) continue;
        line = lower(line);
        // Strip an accidental scheme or wildcard prefix.
        for (const char* p : {"https://", "http://", "*.", "."}) {
            const size_t n = std::char_traits<char>::length(p);
            if (line.compare(0, n, p) == 0) { line = line.substr(n); break; }
        }
        if (line.empty()) continue;
        const size_t slash = line.find('/');
        const std::string host = slash == std::string::npos ? line : line.substr(0, slash);
        if (host.empty() || host.find('.') == std::string::npos) continue;
        if (!std::all_of(host.begin(), host.end(), validDomainChar)) continue;
        if (slash != std::string::npos && slash + 1 < line.size()) {
            if (seenPaths.insert(line).second) list.pathPatterns.push_back(line);
        } else if (seenDomains.insert(host).second) {
            list.domains.push_back(host);   // "host/" is just a host
        }
    }
    return list;
}

const TrackerBlocklist& builtinTrackerBlocklist() {
    static const TrackerBlocklist list = parseTrackerBlocklist(kBuiltinTrackerBlocklistText);
    return list;
}

std::string trackerContentRulesJson(const TrackerBlocklist& list) {
    std::string json = "[";
    bool first = true;
    // The regex is built with real single backslashes, then JSON-escaped
    // (each backslash doubled) when written into the rule document.
    auto jsonEscape = [](const std::string& in) {
        std::string out;
        for (char c : in) { if (c == '\\' || c == '"') out += '\\'; out += c; }
        return out;
    };
    auto rule = [&](const std::string& regex) {
        if (!first) json += ",";
        first = false;
        json += "{\"trigger\":{\"url-filter\":\"" + jsonEscape(regex) +
                "\",\"load-type\":[\"third-party\"]},\"action\":{\"type\":\"block\"}}";
    };
    for (const auto& d : list.domains) {
        // Host boundary: the domain itself or any subdomain, then the end of
        // the authority (path, port or end of string).
        rule("^https?://([^/]+\\.)?" + regexEscape(d) + "[/:]");
    }
    for (const auto& p : list.pathPatterns) {
        const size_t slash = p.find('/');
        rule("^https?://([^/]+\\.)?" + regexEscape(p.substr(0, slash)) +
             regexEscape(p.substr(slash)));
    }
    json += "]";
    return json;
}

std::string trackerRulesIdentifier(const TrackerBlocklist& list) {
    // FNV-1a over the canonical entry list: cheap, stable across runs, and
    // different whenever the list content differs.
    uint64_t h = 1469598103934665603ULL;
    auto mix = [&](const std::string& s) {
        for (unsigned char c : s) { h ^= c; h *= 1099511628211ULL; }
        h ^= '\n'; h *= 1099511628211ULL;
    };
    for (const auto& d : list.domains) mix(d);
    for (const auto& p : list.pathPatterns) mix("/" + p);
    static const char* hex = "0123456789abcdef";
    std::string id = "lethe-trackers-v1-";
    for (int i = 60; i >= 0; i -= 4) id += hex[(h >> i) & 15];
    return id;
}

} // namespace lethe
